# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

java_version=21

neo_form_version=1.21.8-20250717.133445

parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Mod
mod_id=cumulus_menus
mod_group=com.aetherteam.cumulus
mod_name=Cumulus
mod_version=2.0.6
mod_license=LGPL-3.0
mod_url=https://modrinth.com/mod/cumulus
mod_update=https://github.com/The-Aether-Team/Cumulus/raw/1.21.4-develop/update.json
mod_tracker=https://github.com/The-Aether-Team/Cumulus/issues
mod_credits=The Aether Team; kingbdogz, for the original Main Menu API that this is inspired by
mod_authors=AlphaMode, bconlon, Blodhgarm
mod_description=A library for custom menu registration.

minecraft_version=1.21.8
neo_minecraft_version_range=[1.21.8,1.21.9)
fabric_minecraft_version_range=~1.21.8

moddevgradle_version=2.0.105

loom_version=1.11-SNAPSHOT

neo_version=21.8.25

neo_version_range=[21.8.25,)

fabric_version=0.130.0+1.21.8
fabric_loader_version=0.16.14

fabric_version_range=*
fabric_loader_version_range=>=0.16.14

forge_config_version=21.8.0

mixin_extra_version=0.5.0-beta.3

# Publishing
curseforge_id=915473
modrinth_id=sq1f0DCq
version_type=release
