# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

java_version=21

neo_form_version=1.21.11-20251209.172050

parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Mod
mod_id=cumulus_menus
mod_group=com.aetherteam.cumulus
mod_name=Cumulus
mod_version=2.0.11
mod_license=LGPL-3.0
mod_url=https://modrinth.com/mod/cumulus
mod_update=https://github.com/The-Aether-Team/Cumulus/raw/1.21.4-develop/update.json
mod_tracker=https://github.com/The-Aether-Team/Cumulus/issues
mod_credits=The Aether Team; kingbdogz, for the original Main Menu API that this is inspired by
mod_authors=AlphaMode, bconlon, Blodhgarm
mod_description=A library for custom menu registration.

minecraft_version=1.21.11
neo_minecraft_version_range=[1.21.11,26.1)
fabric_minecraft_version_range=~1.21.11

moddevgradle_version=2.0.140

loom_version=1.15-SNAPSHOT

neo_version=21.11.38-beta

neo_version_range=[21.11.38-beta,)

fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.4

fabric_version_range=*
fabric_loader_version_range=>=0.18.4

forge_config_version=21.11.1

mixin_extra_version=0.5.3

# Publishing
curseforge_id=915473
modrinth_id=sq1f0DCq
version_type=release
