name: Publish to CurseForge

on: 
  workflow_dispatch
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: wrapper
    - uses: actions/upload-artifact@v4
      with:
        name: problems-report.html
        path: |
            ~/runner/work/Cumulus/Cumulus/build/reports/problems/
    - name: Publish build
      env:
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      run: |
        if [ "${{ github.event.sender.login }}" = "OscarPayn" ] || [ "${{ github.event.sender.login }}" = "bconlon1" ]; then
          chmod +x ./gradlew
          find ~
          ./gradlew :fabric:curseforge
          ./gradlew :neoforge:curseforge
        fi
